"""Canonical procurement opportunity schema helpers."""
from __future__ import annotations

from typing import Any


RECORD_DOMAIN = "PROCUREMENT_OPPORTUNITY"


def empty_procurement_record() -> dict[str, Any]:
    return {
        "record_domain": RECORD_DOMAIN,
        "procurement_id": None,
        "lifecycle_group_id": None,
        "source_id": "g2b",
        "notice_number": None,
        "notice_revision": None,
        "original_notice_number": None,
        "procurement_stage": None,
        "procurement_status": None,
        "title": None,
        "title_normalized": None,
        "ordering_organization": None,
        "demand_organization": None,
        "announcement_date": None,
        "proposal_deadline": None,
        "opening_date": None,
        "award_date": None,
        "contract_date": None,
        "estimated_amount": None,
        "base_amount": None,
        "contract_amount": None,
        "awardee_organizations": [],
        "consortium_organizations": [],
        "contract_method": None,
        "source_url": None,
        "detail_url": None,
        "attachment_urls": [],
        "request_for_proposal_urls": [],
        "public_contact_department": None,
        "public_contact_name": None,
        "public_contact_email": None,
        "public_contact_phone": None,
        "matched_event_ids": [],
        "matched_event_link_basis": [],
        "matched_previous_procurement_ids": [],
        "previous_cycle_confidence": None,
        "previous_awardees": [],
        "previous_cycle_summary": {},
        "opportunity_routes": [],
        "primary_route": None,
        "direct_bid_fit_path": None,
        "eligibility_status": None,
        "bid_participation_readiness": None,
        "bid_go_no_go": None,
        "sales_windows": [],
        "sales_priority": None,
        "recommended_next_action": None,
        "blocking_unknowns": [],
        "registration_open_status": "UNKNOWN",
        "system_supplier_status": "UNKNOWN",
        "days_to_deadline": None,
        "days_to_event": None,
        "prep_days_award_to_event": None,
        "event_name": None,
        "event_date": None,
        "bid_assessment_applicable": None,
        "bid_assessment_scope_reason": None,
        "source_scope": "G2B_OFFICIAL_OPENAPI",
        "lifecycle_link_basis": [],
        "lifecycle_candidate_links": [],
        "collected_at": None,
        "raw_file": None,
    }
